name: Pipeline Aplication

on:
  push:
    branches: #Ramas
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install -r Requirements.txt
        
    - name: Lint con flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics   
    - name: Run Tests
      run: |
        python manage.py test
    
    - name: Deploy Server
      uses: appleboy/ssh-action@master
      with:
        HOST: "172.26.62.189"
        USERNAME: "lti_test_admin"
        password: "5wGG6M4Ngc"
        PORT: 22
        SCRIPT: |
          whoami
          ls

#Holas
  # deploy:
  #   name: Deploy to EC2 on master branch push
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout the files
  #       uses: actions/checkout@v2

  #     - name: Deploy to Server 1
  #       uses: easingthemes/ssh-deploy@main
  #       env:
  #         SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }} # Este será su .pem archivo que usará para iniciar sesión en la instancia
  #         REMOTE_HOST: ${{ secrets.HOST_DNS }} # Registro DNS público de la instancia, se verá asíec2-xx-xxx-xxx-xxx.us-west-2.compute.amazonaws.com
  #         REMOTE_USER: ${{ secrets.USERNAME }} # Será el nombre de usuario de la instancia EC2, normalmente ubuntu
  #         TARGET: ${{ secrets.TARGET_DIR }} # Es donde desea implementar su código.
